[env]
BINARY="git-calver"

[tools]
go = "1.23"

[settings]
experimental = true
not_found_auto_install = true

[tasks.build]
description = 'Build the CLI'
alias = 'b'
run = """
#!/usr/bin/env bash
echo "Building bin/${BINARY}"
go build -o bin/${BINARY} main.go
cp bin/${BINARY} ~/go/bin/
"""

[tasks.tests]
description = 'Run the tests'
alias = 't'
run = """
#!/usr/bin/env bash
echo "Running Tests"
go test ./...
"""
