on:
  release: {}
  push:
    branches:
      - 'feature/publisher'

name: Build Release
jobs:
  release-linux-386:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: "386"
          goos: linux
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: amd64
          goos: linux
  release-linux-arm:
    name: release linux/386
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: "arm"
          goos: linux
  release-linux-arm64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: arm64
          goos: linux
  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compile and release
        uses: wangyoucao577/go-release-action@v1
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goarch: amd64
          goos: darwin
